version: '3'
services:
  # node:
  #   image: ng_test
  #   ports:
  #     - 4200:4200
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  worker:
    image: scraper
    links:
      - rabbit
    depends_on:
      - rabbit
