
dataHeight = {
    "PrimaryKey" : "v_100",
    "DBKey" : "text",
    "PointLoc" : "float",
    "PointNbr" : "float",
    "RecKey" : "v_100",
    "Height" : "float",
    "Species" : "text",
    "Chkbox" : "float",
    "type" : "text",
    "GrowthHabit_measured" : "text",
    "LineKey" : "v_100",
    "DateModified" : "date",
    "FormType" : "text",
    "FormDate" : "date",
    "Observer" : "text",
    "Recorder" : "text",
    "DataEntry" : "text",
    "DataErrorChecking" : "text",
    "Direction" : "v_100",
    "Measure" : "float",
    "LineLengthAmount" : "float",
    "SpacingIntervalAmount" : "float",
    "SpacingType" : "text",
    "HeightOption" : "text",
    "HeightUOM" : "text",
    "ShowCheckbox" : "float",
    "CheckboxLabel" : "text",
    "source" : "text",
    "UOM" : "text",
    "DateLoadedInDb": "date"
    }
