
dataLPI = {
    "LineKey" : "v_100",
    "RecKey" : "v_100",
    "DateModified" : "date",
    "FormType" : "text",
    "FormDate" : "date",
    "Observer" : "text",
    "Recorder" : "text",
    "DataEntry" : "text",
    "DataErrorChecking" : "text",
    "Direction" : "v_50",
    "Measure" : "float",
    "LineLengthAmount" : "float",
    "SpacingIntervalAmount" : "float",
    "SpacingType" : "text",
    "HeightOption" : "text",
    "HeightUOM" : "text",
    "ShowCheckbox" : "float",
    "CheckboxLabel" : "text",
    "PrimaryKey" : "v_100",
    "DBKey" : "text",
    "PointLoc" : "float",
    "PointNbr" : "float",
    "ShrubShape" : "text",
    "layer" : "text",
    "code" : "text",
    "chckbox" : "integer",
    "source" : "text",
    "STATE" : "v_50",
    "DateLoadedInDb": "text",
    "SAGEBRUSH_SPP": "text",
    "PLOTKEY":"v_100"
}
