
dataSoilStability = {
    "PlotKey" : "v_100",
    "RecKey" : "v_100",
    "DateModified" : "date",
    "FormType" : "text",
    "FormDate" : "date",
    "LineKey" : "v_100",
    "Observer" : "text",
    "Recorder" : "text",
    "DataEntry" : "text",
    "DataErrorChecking" : "text",
    "SoilStabSubSurface" : "float",
    "Notes" : "text",
    "DateLoadedInDb" : "date",
    "PrimaryKey" : "v_100",
    "DBKey" : "text",
    "Position" : "float",
    "Line" : "v_50",
    "Pos" : "v_50",
    "Veg" : "text",
    "Rating" : "float",
    "Hydro" : "float",
    "source" : "text"
}
